version: '3.3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=hibernate
      - POSTGRES_PASSWORD=hibernate
      - POSTGRES_DB=demo-db
    ports:
      - '5432:5432'